### PR TITLE
🐛 Fix bug that BMH NetworkData and MetaData cleaned on deprovisioning when they should not

### LINKED ISSUE #196: BMH NetworkData and userData cleaned on deprovisioning when they should not
**What steps did you take and what happened:**
This bug was raised by the airship project. CAPM3 deletes the content of the networkData and metaData fields even when it does not manage them.

**What did you expect to happen:**
CAPM3 should not always delete those, only when the networkData and metaData fields are set in the status of the metal3machine

**Anything else you would like to add:**
The problem is on line https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/baremetal/metal3machine_manager.go#L513 and https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/baremetal/metal3machine_manager.go#L518 . There should be a check similar to https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/baremetal/metal3machine_manager.go#L924 and https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/baremetal/metal3machine_manager.go#L930

**Environment:**

- Cluster-api version:  NA
- Cluster-api-provider-metal3 version: v0.4.X
- Environment (metal3-dev-env or other): NA
- Kubernetes version: (use `kubectl version`): NA

/kind bug

### PR DESCRIPTION
**Pull request by namnx228**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #196

### CODE REVIEW

File: baremetal/metal3machine_manager.go [hunk 1]
```diff
@@ -510,11 +510,11 @@ func (m *MachineManager) Delete(ctx context.Context) error {
 			host.Spec.UserData = nil
```
Comment (furkatgofurov7) [inline baremetal/metal3machine_manager.go:510]: @maelk what about the `UserData`, is it fine to delete the content of this field?

**Review by furkatgofurov7 — COMMENTED** [review]
This LGTM.

File: baremetal/metal3machine_manager.go (hunk 1 above)
Comment (maelk) [reply baremetal/metal3machine_manager.go:510]: that one is pretty much always present since it comes from CAPI. but we could put the same check there, it would not hurt

File: baremetal/metal3machine_manager_test.go [hunk 2]
```diff
@@ -1397,6 +1397,12 @@ var _ = Describe("Metal3Machine manager", func() {
 					expectedName = tc.ExpectedConsumerRef.Name
 				}
 				Expect(name).To(Equal(expectedName))
+				if machineMgr.Metal3Machine.Status.MetaData == nil {
```
Comment (maelk) [inline baremetal/metal3machine_manager_test.go:1400]: None of the bmh you are working with in the tests have the networkData and metaData set I think, so you should modify bmhSpecSomeImg for example to add it there, so that it is actually tested

**Comment by namnx228** [comment]
Thanks for review, @maelk @furkatgofurov7. I have fixed all change requests. PTAL again

File: baremetal/metal3machine_manager_test.go [hunk 3]
```diff
@@ -1664,6 +1681,17 @@ var _ = Describe("Metal3Machine manager", func() {
 			ExpectSecretDeleted:       true,
 			ExpectClusterLabelDeleted: false,
 		}),
+		Entry("BMH NetworkData and MetaData should not be cleaned on deprovisioning", testCaseDelete{
```
Comment (furkatgofurov7) [inline baremetal/metal3machine_manager_test.go:1684]: maybe UserData too, as you have added it in the `bmhSpecSomeImg`?

**Review by kashifest — APPROVED** [review]

File: baremetal/metal3machine_manager_test.go (hunk 3 above)
Comment (namnx228) [reply baremetal/metal3machine_manager_test.go]: Fixed! Thanks

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm
