### PR TITLE
🐛 remove ipam pool reference defaulting to metal3

### LINKED ISSUE #1010: CAPM3 v1.4.0 fails apply of existing Metal3DataTemplates because of validatingWebhook
**What steps did you take and what happened:**
After Upgrading to v1.4.0 we are seeing our existing Metal3DataTemplate applies being blocked by the validatingWebhook because of the immutability check.
exact failure:
```
Metal3DataTemplate/metal3-refaz-bn/boje-1-cp-metadata-0 dry-run failed, reason: Invalid, error: admission webhook "validation.metal3datatemplate.infrastructure.cluster.x-k8s.io" denied the request: Metal3Data.infrastructure.cluster.x-k8s.io "boje-1-cp-metadata-0" is invalid: spec.MetaData: Invalid value: v1beta1.MetaData{Strings:[]v1beta1.MetaDataString(nil), ObjectNames:[]v1beta1.MetaDataObjectName{v1beta1.MetaDataObjectName{Key:"machine_name", Object:"machine"}, v1beta1.MetaDataObjectName{Key:"metal3machine_name", Object:"metal3machine"}, v1beta1.MetaDataObjectName{Key:"bmh_name", Object:"baremetalhost"}}, Indexes:[]v1beta1.MetaDataIndex(nil), Namespaces:[]v1beta1.MetaDataNamespace(nil), IPAddressesFromPool:[]v1beta1.FromPool{v1beta1.FromPool{Key:"cluster_ip_0", Name:"boje-1-pool-0", APIGroup:"ipam.metal3.io", Kind:"IPPool"}, v1beta1.FromPool{Key:"lan_ip_0", Name:"refaz-bn-lan-pool-0", APIGroup:"ipam.metal3.io", Kind:"IPPool"}}, PrefixesFromPool:[]v1beta1.FromPool{v1beta1.FromPool{Key:"cluster_prefix_0", Name:"boje-1-pool-0", APIGroup:"ipam.metal3.io", Kind:"IPPool"}, v1beta1.FromPool{Key:"lan_prefix_0", Name:"refaz-bn-lan-pool-0", APIGroup:"ipam.metal3.io", Kind:"IPPool"}}, GatewaysFromPool:[]v1beta1.FromPool(nil), DNSServersFromPool:[]v1beta1.FromPool(nil), FromHostInterfaces:[]v1beta1.MetaDataHostInterface(nil), FromLabels:[]v1beta1.MetaDataFromLabel(nil), FromAnnotations:[]v1beta1.MetaDataFromAnnotation(nil)}: cannot be modified
```
The offending resource hasnt been modified in git for the last 9 months.

**What did you expect to happen:**
The ValidatingWebhook works correctly

**Anything else you would like to add:**
<details open><summary>In cluster resource</summary>

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  creationTimestamp: "2022-10-14T16:10:36Z"
  finalizers:
  - metal3datatemplate.infrastructure.cluster.x-k8s.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: tenant-clusters-metal3-refaz-bn
    kustomize.toolkit.fluxcd.io/namespace: schiff-system
  name: boje-1-cp-metadata-0
  namespace: metal3-refaz-bn
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    controller: false
    kind: Cluster
    name: boje-1
    uid: f874f40d-51bf-4884-8c63-15d72175366c
  resourceVersion: "2247637014"
  uid: a4172840-e99b-4a84-95de-e6e32bed945c
spec:
  clusterName: boje-1
  metaData:
    ipAddressesFromIPPool:
    - key: cluster_ip_0
      name: boje-1-pool-0
    - key: lan_ip_0
      name: refaz-bn-lan-pool-0
    objectNames:
    - key: machine_name
      object: machine
    - key: metal3machine_name
      object: metal3machine
    - key: bmh_name
      object: baremetalhost
    prefixesFromIPPool:
    - key: cluster_prefix_0
      name: boje-1-pool-0
    - key: lan_prefix_0
      name: refaz-bn-lan-pool-0
  networkData:
    links: {}
    networks: {}
    services:
      dns:
      - 10.102.102.132
      - 10.102.102.133
      - 10.90.24.1
      - 10.90.24.17
status:
  lastUpdated: "2023-05-31T09:30:24Z"
  ```
</details>
<details open><summary>Resource in git</summary>

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: boje-1-cp-metadata-0
  namespace: metal3-refaz-bn
spec:
  clusterName: boje-1
  metaData:
    ipAddressesFromIPPool:
    - key: cluster_ip_0
      name: boje-1-pool-0
    - key: lan_ip_0
      name: refaz-bn-lan-pool-0
    objectNames:
    - key: machine_name
      object: machine
    - key: metal3machine_name
      object: metal3machine
    - key: bmh_name
      object: baremetalhost
    prefixesFromIPPool:
    - key: cluster_prefix_0
      name: boje-1-pool-0
    - key: lan_prefix_0
      name: refaz-bn-lan-pool-0
  networkData:
    links: {}
    networks: {}
    services:
      dns:
      - 10.102.102.132
      - 10.102.102.133
      - 10.90.24.1
      - 10.90.24.17

```
</details>

**Environment:**

- Cluster-api version: latest
- Cluster-api-provider-metal3 version: v1.4.0
- Environment (metal3-dev-env or other): other
- Kubernetes version: (use `kubectl version`): v1.23.17

/kind bug

### PR DESCRIPTION
**Pull request by schrej**
**What this PR does / why we need it**:
#769 introduced defaulting for IPAM pool references that changes group and kind to metal3 IPAM. Since Metal3DataTemplates are immutable, this causes issues with existing resources when they are continuously applied (gitops).

The easiest option is to remove the defaulting in the webhook, since there are two more instances of defaulting in the DataManager ([here](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3data_manager.go#L400) and [here](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3data_manager.go#L434)).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1010

### CODE REVIEW

File: api/v1beta1/metal3datatemplate_webhook.go [hunk 1]
```diff
@@ -39,53 +37,7 @@ func (c *Metal3DataTemplate) SetupWebhookWithManager(mgr ctrl.Manager) error {
...
-		}
-
-		for k, network := range c.Spec.NetworkData.Networks.IPv6 {
-			if network.FromPoolRef != nil && network.FromPoolRef.Name != "" {
-				defaultRefToM3IPAM(c.Spec.NetworkData.Networks.IPv6[k].FromPoolRef)
-			}
-		}
-	}
-}
+func (c *Metal3DataTemplate) Default() {}
```
Comment (lentzi90) [inline api/v1beta1/metal3datatemplate_webhook.go:40]: Perhaps a comment here to explain why it isn't doing anything would be good?

Comment (lentzi90) [reply api/v1beta1/metal3datatemplate_webhook.go:40]: Good point. No need to add it.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
@mboukhalfa what is blocking us to merge this, since I see required jobs are passing?

**Comment by mboukhalfa** [comment]
> I think that is because #769 is merged into main where it introduced defaulting for IPAM pool references whereas v1.4 still uses the old defaulting.
 
 Actually #769 is implemented in 1.4.0 check here https://github.com/metal3-io/cluster-api-provider-metal3/releases/tag/v1.4.0

**Comment by schrej** [comment]
> I think that is because #769 is merged into main where it introduced defaulting for IPAM pool references whereas v1.4 still uses the old defaulting. Also, @schrej I don't recall the reason behind, but why we had to introduce `IPAddressesFromPool` in #769 when we had `IPAddressesFromIPPool` already

I assume the question was supposed to be why we added `FromPoolRef` even though we already had `IPAddressesFromIPPool`.

The reason is that `IPAddressFromIPPool` is a string, and there is no nice way to extend that with Group/Kind information. That's why I've added a new field as an alternative.

For other fields, which were using the `FromPool` struct I just added new fields, but those fields are required, which leads to the issue we're seeing here.

**Comment by mboukhalfa** [comment]
> For other fields, which were using the `FromPool` struct, I just added new fields, but those fields are required, which leads to the issue we're seeing here.

What confuses me is that the template applied on the bootstrap cluster works but when we apply workload template on the target cluster it fails I still do not understand the difference :/

**Comment by tuminoid** [comment]
Overriding unrelated test failures per @mboukhalfa's request.

/override keep-test-e2e-upgrade-from-release-1-4 
/override test-e2e-upgrade-main-from-release-1-4
