### PR TITLE
:bug: Multiple updates operation on the BMH #33

### LINKED ISSUE #33: Multiple updates operation on the BMH
**What steps did you take and what happened:**
Currently, CAPM3 can execute multiple update operations on the BMH. This is problematic because the update triggers a reconcile of the BMH while we still process the BMH, regularly ending in a conflict, triggering a requeue.

**What did you expect to happen:**
We should postpone the update operations as much as possible to do only one update per reconciliation of the Metal3machine maximum.

/kind bug

### PR DESCRIPTION
**Pull request by mikkosest**
**What this PR does / why we need it**:
Currently, CAPM3 can execute multiple update operations on the BMH. This is problematic because the update triggers a reconcile of the BMH while we still process the BMH, regularly ending in a conflict, triggering a requeue.
 
Fixes #33

### CODE REVIEW

File: controllers/metal3machine_controller_test.go [hunk 1]
```diff
@@ -74,7 +74,6 @@ func setReconcileNormalExpectations(ctrl *gomock.Controller,
 	if tc.BootstrapNotReady {
 		m.EXPECT().HasAnnotation().MaxTimes(0)
 		m.EXPECT().GetBaremetalHostID(context.TODO()).MaxTimes(0)
-		m.EXPECT().Update(context.TODO()).MaxTimes(0)
```
Comment (maelk) [inline controllers/metal3machine_controller_test.go]: why removing it from here ? if bootstrap is not ready, Update should not be called (neither Associate btw).

File: controllers/metal3machine_controller_test.go [hunk 2]
```diff
@@ -85,19 +84,20 @@ func setReconcileNormalExpectations(ctrl *gomock.Controller,
 		if tc.AssociateFails {
 			m.EXPECT().Associate(context.TODO()).Return(errors.New("Failed"))
 			m.EXPECT().GetBaremetalHostID(context.TODO()).MaxTimes(0)
-			m.EXPECT().Update(context.TODO()).MaxTimes(0)
 			return m
 		} else {
 			m.EXPECT().Associate(context.TODO()).Return(nil)
+			m.EXPECT().Update(context.TODO()).MaxTimes(0)
```
Comment (maelk) [inline controllers/metal3machine_controller_test.go]: In both cases Update should not be called, so you can add `m.EXPECT().Update(context.TODO()).MaxTimes(0)` outside of the if/else block

File: controllers/metal3machine_controller_test.go [hunk 3]
```diff
@@ -85,19 +84,20 @@ func setReconcileNormalExpectations(ctrl *gomock.Controller,
...
 		}
+	} else {
+		m.EXPECT().Update(context.TODO()).MaxTimes(2)
```
Comment (maelk) [inline controllers/metal3machine_controller_test.go]: why max times 2 ? if it should be called, remove the MaxTimes, it will ensure that it is called at least once.

Comment (mikkosest) [reply controllers/metal3machine_controller_test.go]: Fixed

File: controllers/metal3machine_controller_test.go (hunk 2 above)
Comment (mikkosest) [reply controllers/metal3machine_controller_test.go]: Fixed

File: controllers/metal3machine_controller_test.go (hunk 1 above)
Comment (mikkosest) [reply controllers/metal3machine_controller_test.go]: Fixed

**Comment by maelk** [comment]
don't forget to submit the same for the branch release-0.3
