### PR TITLE
🐛 Fix shell parameters expansion for CAPI deployment

### LINKED ISSUE #125: CAPI isn't deployed correctly after "make deploy"
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I use fresh K8s cluster deployed with GCP Kubernetes engine
Performing **make deploy** in fresh cloned metal3-io/cluster-api-provider-metal3 repo
results in
```
capi-kubeadm-bootstrap-controller-manager-5bdc7dbf5d-d5ml5     CrashLoopBackOff
capi-controller-manager-7894bbf65d-hq9xc                       CrashLoopBackOff
capi-controller-manager-6dd9f648cf-zf2hw                       CrashLoopBackOff
capi-kubeadm-bootstrap-controller-manager-867f46d767-k4862     CrashLoopBackOff
```

```
kubectl logs capi-controller-manager-7894bbf65d-hq9xc manager -n capi-system
invalid argument "MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false}" for "--feature-gates" flag: invalid value of MachinePool=${EXP_MACHINE_POOL:=false}, err: strconv.ParseBool: parsing "${EXP_MACHINE_POOL:=false}": invalid syntax

```
**What did you expect to happen:**
CAPI controllers up and running

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Probably it's related to https://github.com/kubernetes-sigs/cluster-api/issues/3339
but I don't understand what is exactly wrong in my case. I don't see any clusterctl uses during **make deploy**

**Environment:**

- Cluster-api version: 0.3.7
- CAPBM version:
- Minikube version:
- environment (metal3-dev-env or other): GCP Kubernetes engine
- Kubernetes version: (use `kubectl version`): v1.17.8-gke.17

/kind bug

### PR DESCRIPTION
**Pull request by DmitryGrayscale**
**What this PR does / why we need it**:
In CAPI v0.3.7+ yaml files expressions like ${PARAM:=DEFAULTVALUE} were added.
GNU envsubst can't handle such kind of expressions, so enhnaced
implementation of envsubst were used to overcome this.

**Which issue(s) this PR fixes**:
Fixes #125

### CODE REVIEW

File: examples/generate.sh [hunk 1]
```diff
@@ -114,16 +114,20 @@ echo "Generated ${MACHINEDEPLOYMENT_GENERATED_FILE}"
 # Get Cert-manager provider components file
 curl -L -o "${COMPONENTS_CERT_MANAGER_GENERATED_FILE}" https://github.com/jetstack/cert-manager/releases/download/v0.13.0/cert-manager.yaml
 
+# Get enhanced envsubst version to evaluate expressions like ${VAR:=default}
+curl -L -o envsubst-go https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m`
+chmod +x envsubst-go
```
Comment (maelk) [inline examples/generate.sh:119]: Should this be in a specific folder ? like a tmp, or the examples folder, rather than where this script is executed from ?

File: examples/generate.sh [hunk 2]
```diff
@@ -114,16 +114,20 @@ echo "Generated ${MACHINEDEPLOYMENT_GENERATED_FILE}"
...
+
 # Generate Cluster API provider components file.
-"$KUSTOMIZE" build "github.com/kubernetes-sigs/cluster-api/config/?ref=master" > "${COMPONENTS_CLUSTER_API_GENERATED_FILE}"
+"$KUSTOMIZE" build "github.com/kubernetes-sigs/cluster-api/config/?ref=master" | ./envsubst-go > "${COMPONENTS_CLUSTER_API_GENERATED_FILE}"
```
Comment (maelk) [inline examples/generate.sh:122]: most variables in the manifests are not defined when we call envsubst. You could define a set of default variable used just to populate the example manifests.

Comment (DmitryGrayscale) [reply examples/generate.sh]: Yes, it should be like that :)
By the way, do you think that replacing "vanilla" envsubst entirely with the "enhanced" version could be a thing there?
With the PR we will use two different envsubst when one of them just supports both use cases.

File: examples/generate.sh (hunk 1 above)
Comment (DmitryGrayscale) [reply examples/generate.sh]: Yes, it should be like that :)
By the way, do you think that replacing "vanilla" envsubst entirely with the "enhanced" version could be a thing there?
With the PR we will use two different envsubst when one of them just supports both use cases.

File: examples/generate.sh (hunk 2 above)
Comment (DmitryGrayscale) [reply examples/generate.sh]: I didn't quite understood you probably, added the following just in case 
https://github.com/metal3-io/cluster-api-provider-metal3/pull/126/commits/6bbfb1b8d5d90b43fff5df66e8ea13c99ac1d328#diff-2b085cd4a651deec0d4f1b1850814f02R43-R44

Comment (maelk) [reply examples/generate.sh]: I didn't see that they are now with a default within the manifests, sorry, my bad.

Comment (DmitryGrayscale) [reply examples/generate.sh]: yes, I will remove default values from the generate.sh then
