### PR TITLE
🌱Bump golangci-lint to v2.8.0 for Go 1.25.x support

### LINKED ISSUE #3067: Golangci-lint crashes if run in CAPM3 repo and local go is 1.25.x
Btw, golangci-lint crashes if run in CAPM3 repo and local go is 1.25. We should bump it.

_Originally posted by @tuminoid in https://github.com/metal3-io/cluster-api-provider-metal3/issues/3059#issuecomment-3738085039_

Bump the GH action and the local version to be the same. Probably latest with support to Go 1.25 is the way to go.

### PR DESCRIPTION
**Pull request by neeraj542**
## Description
This PR updates golangci-lint from v2.1.0 to v2.8.0 to support Go 1.25.x, fixing the crash issue when running golangci-lint with Go 1.25.x.

## Changes
- Updated GitHub Actions workflow to use golangci-lint v2.8.0
- Updated local installation script to v2.8.0 with new SHA256 checksums for darwin-arm64 and linux-amd64
- Fixed all new linter issues introduced by v2.8.0:
  - Replaced exec.Command with exec.CommandContext (13 noctx issues)
  - Optimized string concatenation using strings.Join (1 perfsprint issue)
  - Preallocated slices with appropriate capacity (13 prealloc issues)

## Testing
- Both GitHub Actions workflow and local script now use the same version (v2.8.0)
- SHA256 checksums verified for both platforms
- All lint errors resolved

Fixes #3067

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
/retitle 🌱Bump golangci-lint to v2.4.0 for Go 1.25.x support

**Comment by neeraj542** [comment]
thanks for pointing that out! you're absolutely right, we should use the latest version. I'll update the PR to use v2.8.0 instead of v2.4.0. Updating now.

> Newest version is 2.8.0, any reason not to take that?

**Comment by neeraj542** [comment]
> Newest version is 2.8.0, any reason not to take that?

Thanks @tuminoid for the feedback! I've updated to v2.8.0 as suggested.

**Comment by tuminoid** [comment]
Now, the bonus part is fixing the new linter issues that come with newer version :) They look simple though.

**Comment by neeraj542** [comment]
> Now, the bonus part is fixing the new linter issues that come with newer version :) They look simple though.

Done.. all the new linter issues from v2.8.0 have been fixed. The PR should now pass all checks.

File: controllers/metal3labelsync_controller.go [hunk 1]
```diff
@@ -381,13 +381,19 @@ func RegexError(msg string, fmt string, examples ...string) string {
...
-	msg += "regex used for validation is '" + fmt + "')"
-	return msg
+		b.WriteString("'")
+		b.WriteString(examples[i])
+		b.WriteString("', ")
+	}
+	b.WriteString("regex used for validation is '")
+	b.WriteString(fmt)
+	b.WriteString("')")
+	return b.String()
```
Comment (tuminoid) [inline controllers/metal3labelsync_controller.go]:
```suggestion
return msg + " (e.g. '" + strings.Join(examples, "' or '") + "', regex used for validation is '" + fmt + "')"
```

**Review by tuminoid — COMMENTED** [review]
Please fix the discrepancies in PR title and description as noted by Copilot, and then see the suggestion for the labelsync controller.

/cc @adilGhaffarDev @lentzi90

**Comment by neeraj542** [comment]
Could you please advise if we should expedite this process, so I can align accordingly?

> Please fix the discrepancies in PR title and description as noted by Copilot, and then see the suggestion for the labelsync controller.
> 
> /cc @adilGhaffarDev @lentzi90

**Comment by tuminoid** [comment]
> Could you please advise if we should expedite this process, so I can align accordingly?

Now sure what you're asking? Most tests are passing, e2e is running, and just one code simplification with replacement suggestion available and making PR title/desc match?

**Comment by neeraj542** [comment]
Hi @tuminoid, thanks for the guidance!

all requested changes are completed:
- Updated PR title and description to reflect v2.8.0 (was v2.4.0)
- Simplified RegexError function to use strings.Join as suggested
- All lint checks passing
- All code checks passing

The PR is now ready for review. E2E tests are running as requested. Please let me know if you need any other changes.

**Comment by tuminoid** [comment]
> Hi @tuminoid, thanks for the guidance!
> 
> all requested changes are completed:
> 
> * Updated PR title and description to reflect v2.8.0 (was v2.4.0)
> * Simplified RegexError function to use strings.Join as suggested
> * All lint checks passing
> * All code checks passing
> 
> The PR is now ready for review. E2E tests are running as requested. Please let me know if you need any other changes.

Thanks! Can you squash the commits now (either all in one, or the bump in first, and linter fixes in 2nd). I'll trigger e2e then again.

**Comment by neeraj542** [comment]
Thanks for the review! Appreciate it.
I’ll take a look at IPAM, BMO, and IRSO as well. If everything looks good here, could you please merge this PR?

cc: @tuminoid, @adilGhaffarDev , @Rozzii

**Comment by neeraj542** [comment]
Thnks everyone for merging my first PR in **metal3-io**, I would be happy to help and update golangci-lint in IPAM, BMO, and IRSO repos as well to keep them in sync.

Should I:
1. Open issues in those repos first, or
2. can go ahead and create PRs directly?

I can follow the same approach we used here (bump to v2.8.0 + fix linter issues). Let me know your preference!

cc: @adilGhaffarDev @tuminoid @Rozzii
