### PR TITLE
🐛Enable Mariadb instead of SQLite

### LINKED ISSUE #1082: [Flaky Test] Ironic database is locked
### Which jobs are flaking?
 Multiple jobs including:

-  [Clusterctl upgrade](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-0-5_main_e2e_clusterctl_upgrade_test_ubuntu/)
- [BML integration](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-1-4_main_e2e_clusterctl_upgrade_test_ubuntu/45/)
- [Feature test - Pivoting based tests](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_e2e_feature_test_centos/161/)

### Which tests are flaking?
Multiple tests when ironic is involved for inspection or cleaning 

- [04_verify.sh](https://github.com/metal3-io/metal3-dev-env/blob/main/04_verify.sh) 
- [Clusterctl_upgrade](https://github.com/kubernetes-sigs/cluster-api/blob/7b92ce4577e36adf013dc1dfd2b239fde4c36bc4/test/e2e/clusterctl_upgrade.go#L557C17-L557C17) when deleting the cluster

### Since when has it been flaking?
First occurrence noticed Jun 30, 2023, 4:30:00 AM EEST https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_release-1-2_integration_test_centos/303/console

### Reason for failure (if possible)
Ironic database is locked

Event logs in from the tarball path `_artifacts/clusters/bootstrap/resources/clusterctl-upgrade-kprxc0/` in [this Jenkins test link](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-0-5_main_e2e_clusterctl_upgrade_test_ubuntu/34/)
```
[New Event] clusterctl-upgrade-kprxc0/InspectionError-hxbtr
        resource: metal3.io/v1alpha1/BareMetalHost/node-1
        reason: InspectionError
        message: Unexpected exception HttpException during processing: HttpException: 500: Server Error for url: https://172.22.0.2:6385/v1/nodes/fbbcf188-af91-431d-af65-aa2cddf31ef0, (sqlite3.OperationalError) database is locked
```
Ironic logs from the tarball path `docker/after_pivoting/ironic` from [this job link](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-1-4_main_e2e_clusterctl_upgrade_test_ubuntu/45/)
```
2023-07-09 02:44:44.529 1 DEBUG sushy.connector [None req-cd7396e9-c634-4301-beed-d1d045cf4e91 - - - - - -] HTTP request: GET http://192.168.111.1:8000/redfish/v1/Systems/d8f37d44-fb73-4e98-a539-8d4540dbb71c; headers: {'OData-Version': '4.0'}; body: None; blocking: False; timeout: 60; session arguments: {}; _op /usr/lib/python3.9/site-packages/sushy/connector.py:144[00m
2023-07-09 02:44:44.531 1 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6230 -U admin -R 1 -N 5 -f /tmp/tmp3tu4qg4j power status execute /usr/lib/python3.9/site-packages/oslo_concurrency/processutils.py:384[00m
2023-07-09 02:44:44.540 1 ERROR ironic.conductor.base_manager [-] Error while heartbeating. Error: (sqlite3.OperationalError) database is locked
```
Ironic logs from tarball path [`k8s_management_cluster/baremetal-operator-system/baremetal-operator-ironic-7d45f766f7-xb96f/ironic/`] in [this job link](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_bml_integration_tests_centos/473/)
```
2023-07-10 04:09:11.546 1 ERROR ironic.conductor.utils [None req-cc9f0ab0-041b-48fc-b27d-d4b35f481d40 - - - - - -] Failed to prepare node 6e2d9ac1-7c7e-4b3e-b1f0-e1563de5b422 for cleaning: (sqlite3.OperationalError) database is locked
```

### Anything else we need to know?
The issue has been reported to the ironic community, and there is a potential fix available :
https://review.opendev.org/c/openstack/ironic/+/888188
https://review.opendev.org/c/openstack/ironic/+/887853

/kind flake

### PR DESCRIPTION
**Pull request by smoshiur1237**
This PR will enable the Mariadb for ironic instead of SQLite, as we have database lock issue with SQLite. Community suggested to use Mariadb to resolve the issue in  CI. We can move back to SQLite once the issue is fixed from ironic.
Workaround for [#1082](https://github.com/metal3-io/cluster-api-provider-metal3/issues/1082) and keep the issue open to track the fixes of the SQLite issue

### CODE REVIEW

**Comment by mboukhalfa** [comment]
> Fixes #1082
I would just say it is a workaround for #1082 and keep the issue open to track the fixes of the sqlite issue

File: scripts/ci-e2e.sh [hunk 1]
```diff
@@ -20,12 +20,14 @@ M3_DEV_ENV_PATH="${M3_DEV_ENV_PATH:-${WORKING_DIR}/metal3-dev-env}"
...
 
 # Config devenv
+# Enabling Mariadb instead of SQLite. This can be set to false once SQLite issue is resolved
 cat <<-EOF >"${M3_DEV_ENV_PATH}/config_${USER}.sh"
 export CAPI_VERSION=${CAPI_VERSION:-"v1beta1"}
 export CAPM3_VERSION=${CAPM3_VERSION:-"v1beta1"}
 export NUM_NODES=${NUM_NODES:-"4"}
 export KUBERNETES_VERSION=${KUBERNETES_VERSION}
 export IMAGE_OS=${IMAGE_OS}
+export IRONIC_USE_MARIADB=${IRONIC_USE_MARIADB:-"true"}
```
Comment (mboukhalfa) [inline scripts/ci-e2e.sh:30]: Well defaulting will be overridden by infra ! I guess we can hard-code it here ? 

```suggestion
export IRONIC_USE_MARIADB="true"
```

Comment (smoshiur1237) [reply scripts/ci-e2e.sh]: Thanks good point and added the change.

**Comment by mboukhalfa** [comment]
> /test-ubuntu-integration-main
I think we should override the ansible test because it can fail since still using sqlite until project infra changes merged

**Comment by smoshiur1237** [comment]
> > /test-ubuntu-integration-main
> 
> I think we should override the ansible test because it can fail since still using sqlite until project infra changes merged

I have checked the CI run, the variable is set to true.

**Review by furkatgofurov7 — APPROVED** [review]

**Review by Rozzii — APPROVED** [review]
